### ISSUE TITLE
[cppfs] The build fails

### ISSUE THREAD

**Issue by acxz** [acxz/pkgbuilds#1]
upstream issue: https://github.com/cginternals/cppfs/issues/30

**Comment by acxz** [comment]
Closing this issue, since issues for this package still live on the AUR.

**Comment by scheibel** [comment]
The issue is resolved for the current cppfs master. Is a new release required?

**Comment by acxz** [comment]
Thx for fixing the issue! Yes since the package is `cppfs` instead of `cppfs-git` it will only be updated with a new release. However, I have stopped maintaining this package, as such the correct place to post this question is at: https://aur.archlinux.org/packages/cppfs, where the current maintainer can fix it up.
