### ISSUE TITLE
[Gazebo] protobuf version conflict

### ISSUE THREAD

**Issue by elsuizo** [acxz/pkgbuilds#118]
Hi with the last update of Arch the version of protobuf becomes `.so.26` and gazebo needs the version `.so.23`

```text
/usr/bin/ld: warning: libprotobuf.so.23, needed by /opt/ros/noetic/lib/libgazebo_ros_api_plugin.so, not found (try using -rpath or -rpath-link)
```
the trick of simlink
```bash
sudo ln -s /usr/lib/libprotobuf.so.26 /usr/lib/libprotobuf.so.23
```
in this case don't work because a change in the API

**Comment by acxz** [comment]
I believe you would have to rebuild gazebo. Can you try `yay -Rns gazebo` and then `yay -Syu gazebo --rebuildtree`?

**Comment by elsuizo** [comment]
the first command don't work because require more package to delete and with the later command the errors persist

**Comment by acxz** [comment]
If we look at the error message, the actual error is being triggered on `gazebo-ros-api-plugin` which is not part of `gazebo`.  Essentially even gazebo 'deps' need to be rebuilt.

Can you confirm that you are attempting a clean rebuild of gazebo and all its AUR deps?

**Comment by elsuizo** [comment]
the only solution I found is to compile everything again: `yay -S ros-noetic-desktop-full --rebuildtree`

I think the problem is that when we do it only for gazebo it does not update the package `gazebo-ros-api-plugin`
