### ISSUE TITLE
[qgroundcontrol] failure to build with gcc 11

### ISSUE THREAD

**Issue by acxz** [acxz/pkgbuilds#125]
upstream issue: https://github.com/mavlink/qgroundcontrol/issues/9669

**Comment by acxz** [comment]
Patched with: https://github.com/mavlink/gst-plugins-good/pull/1

**Comment by AndKe** [comment]
I need to follow this issue too - can't build with video support right now.

**Comment by acxz** [comment]
Closing issue as fix incorporated in upstream
