### ISSUE TITLE
[ignition-msgs] Add tinyxml2 as Dep

### ISSUE THREAD

**Issue by bionade24** [acxz/pkgbuilds#13]
```
-- Looking for tinyxml2 - not found

-- BUILD ERRORS: These must be resolved before compiling.
--      Missing: tinyxml2
-- END BUILD ERRORS

CMake Error at /usr/share/cmake/ignition-cmake2/cmake2/IgnConfigureBuild.cmake:66 (message):
  Errors encountered in build.  Please see BUILD ERRORS above.
Call Stack (most recent call first):
  CMakeLists.txt:56 (ign_configure_build)


-- Configuring incomplete, errors occurred!
See also "/build/src/ignitionrobotics-ign-msgs-bedb5065b7f4/build/CMakeFiles/CMakeOutput.log".
See also "/build/src/ignitionrobotics-ign-msgs-bedb5065b7f4/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
Building of ignition-msgs failed
```

**Comment by bionade24** [comment]
tinyxml is needed as version 2, not one. Maybe you should build your packages in chroots.

**Comment by acxz** [comment]
thanks for pointing this out, I'll get around to it later tonight.

Yeah I need to learn how to do that. Do you think it is possible for you to add a REAMDE or documentation for your scripts in your aur-ci repo? That would really help me get set up.

**Comment by bionade24** [comment]
Yeah, I probably should do that soon, onto other improvements. (Current plan: Build Web view, build packages in order, central config for Github API key and building backend). As long maybe just look into the Arch Wiki about [how to build in chroots](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot).

**Comment by acxz** [comment]
o.O sounds exciting looking forward to it.
Thanks for the link, things are busy with my academics right now, but once I have the time I really do need to do that.

**Comment by acxz** [comment]
update is out, let me know if you face any other issues!
