### ISSUE TITLE
[cegui] Build error on version 0.8.7

### ISSUE THREAD

**Issue by navti** [acxz/pkgbuilds#133]
Build fails. It requires compiler and library support for ISO C++ 2011 standard. Requires -std=c++11 or -std=gnu++11 compiler option.
![image](https://user-images.githubusercontent.com/13915191/123110476-c2c80b80-d459-11eb-8254-6866d3eea1fc.png)

**Comment by acxz** [comment]
@navti thanks for reporting.
I don't have much time but send a PR my way and I'll merge and sync to the AUR.

**Comment by navti** [comment]
@acxz Thanks! I've raised a PR. Please check and merge.
