### ISSUE TITLE
[python-vispy] Wrong checksum

### ISSUE THREAD

**Issue by JKAbrams** [acxz/pkgbuilds#136]
$ sha256sum python-vispy-0.7.1.tar.gz 
43bf814111b1e33ee04ec0325099702d7ff035deb7c695f2a485ea957d6d79c4  python-vispy-0.7.1.tar.gz

---
PKGBUILD:

sha256sums=('0b17b0f80bee7db242154406c0de35b26d4ece0826fe0d4be16971e86bd11a28'
            '2f10454096cb1ebfa14bd76109fa9ec729f3866307eb990bb66dad1012938c4f')

**Comment by acxz** [comment]
srry about that fixed with f6bc3ff and synced to AUR
