### ISSUE TITLE
[hipsycl-cpu] out of date

### ISSUE THREAD

**Issue by hdclark** [acxz/pkgbuilds#141]
Hi!

The [`hipsycl-cpu` package in the AUR](https://aur.archlinux.org/packages/hipsycl-cpu/) is currently outdated. It targets 0.8.0-1. Attempting to install fails due to not being able to find LLVM 8 or 9.

I see 0.9.1 has been released, but I'm not sure where to find the [repositories mentioned in the installation guide](https://github.com/illuhad/hipSYCL/blob/develop/install/scripts/README.md#installing-from-repositories). Do these repositories refer to the AUR package for Arch Linux?

Thanks!

**Comment by acxz** [comment]
thx for reporting!
updated and synced to the AUR
91c7f01
