### ISSUE TITLE
OpenVSP 3.25.0 does not compile on Manjaro Linux from AUR unless "cp -r python" line is removed from PKGBUILD

### ISSUE THREAD

**Issue by Jdude311** [acxz/pkgbuilds#144]
Like the title says. The program will not compile unless the line containing "cp -r python" is removed from the PKGBUILD.

**Comment by acxz** [comment]
I see, since it seems like many people I have gone ahead and removed the `cp -r python` line. Sorry for delaying this. Please comment on this issue or open another if the problem persists.
