### ISSUE TITLE
[openvsp] Build Error 

### ISSUE THREAD

**Issue by vldw** [acxz/pkgbuilds#146]
I have been trying to install openvsp via yay and can't seem to make it work.

```
[ 24%] Linking CXX static library libutil.a
[ 24%] Built target util
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: openvsp```

**Comment by acxz** [comment]
Can you make sure you are performing a clean build? I just did a clean build (with yay) and it worked fine on my machine.

Also can you post the entire build output. The error isn't apparent from the lines posted.

**Comment by DavidAnderegg** [comment]
I do have exactly the same problem. Here is my build log: [openvsp_build.log](https://github.com/acxz/pkgbuilds/files/7134635/openvsp_build.log)

**Comment by vldw** [comment]
I have tried installing the package with `yay -Syyu openvsp --rebuild` and `yay -Syyu openvsp --rebuildtree` with no luck.
Here is a dump of my output [openvsp.log](https://github.com/acxz/pkgbuilds/files/7134976/openvsp.log).

**Comment by vldw** [comment]
I have found the location of the **Makefile**  in `/.cache/yay/openvsp/src/build/Makefile` that seems to be the problem [Makefile.log](https://github.com/acxz/pkgbuilds/files/7135061/Makefile.log).
Going back to the build log line 156 `$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all` is where it stops.

**Comment by acxz** [comment]
@DavidAnderegg thanks for the build logs.
@vldw it seems like the log you posted has been cut short, I am still not able to see where the error occurs.

@vldw Please refrain from using `-Syyu` if not needed and instead simply use `-Syu`. It causes unnecessary load on mirrors.

As for the error in @DavidAnderegg log. It was previously addressed here: https://github.com/acxz/pkgbuilds/issues/142
Remember to always search past issues.

I'm not sure why and/if `-Wformat-security` is a default flag on your systems, as it isn't in mine and I have not changed my flags from base install.
However, considering that at least 3 users have encountered this error, I believe a patch for this is appropriate. I'll add a patch and try to get it upstream'd.

**Comment by acxz** [comment]
For now I'll close this as a dup and reopen the convo in the previous thread.

**Comment by DavidAnderegg** [comment]
@acxz Thank you! I did not realize this is the same problem.
