### ISSUE TITLE
ignition-gazebo package is out of sync with ecosystem

### ISSUE THREAD

**Issue by Spaceface16518** [acxz/pkgbuilds#149]
You have packaged `ignition-gazebo` at an older release (codename citadel) but the dependency packages have been updated, so gazebo is no longer building. Can `ignition-gazebo` (and the rest of the `ignition-` packages you own) be updated to the latest release (codename edifice)?

AFAIK, no install instructions have changed, so it should be a simple migration. You might also want to leave behind explicitly versioned packages to cover the citadel release (e.g. `ignition-gazebo-4`)

**Comment by Spaceface16518** [comment]
A list of the out of date packages:

- ignition-sensors
- ignition-rendering
- ignition-physics
- ignition-gui
- ignition-gazebo
- ignition-fuel_tools

**Comment by acxz** [comment]
Thx for reminder!

As a sidenote, to make this process easier for the community you can always send PRs to this repo with changes to the PKGBUILDS/SRCINFO files and it'll be much faster for me to push it to the AUR.

> You might also want to leave behind explicitly versioned packages to cover the citadel release (e.g. ignition-gazebo-4)

I used to do this in the past, but might not do it as I have gotten lazy over time, especially if I have not personally using the package. :)

**Comment by Spaceface16518** [comment]
Oh okay, thank you. I appreciate the update.
