### ISSUE TITLE
[hipsycl-rocm] Update PKGBUILD to comply with new packages

### ISSUE THREAD

**Issue by kub0x** [acxz/pkgbuilds#152]
Hello, there has been a recent update of rocm packages in the repository rocm-arch (https://github.com/rocm-arch/rocm-arch) so some of the dependencies found in the package hipsycl-rocm (https://aur.archlinux.org/packages/hipsycl-rocm/) are not being used anymore. These are:

- hip-rocclr renamed to rocm-language-runtime
- rocm to rocm-core

With the dependency hipcpu satisfied, then just do 'makepkg -Acs' and install manually by 'pacman -U <tar_goes_here>' and we're done.

Compiling an example test with syclcc compiler works as intended, so this procedure fixes the package.

**Comment by PetitMote** [comment]
Hello
I guess it’s the same problem with the nvidia version, which would need the hip-nvidia-runtime now, and no longer the hip-nvcc

**Comment by acxz** [comment]
Thanks for the reports and sorry for the long response time. The `hip-sycl-rocm` and `hip-sycl-cuda` packages have been updated along with the dep names.
