### ISSUE TITLE
Python 3.10 rebuild

### ISSUE THREAD

**Issue by Jakeler** [acxz/pkgbuilds#156]
Python 3.10 just got moved from staging to the main stable repos. As always with major py releases the default module path changes, now to `/usr/lib/python3.10/site-packages`, so a rebuild of all modules is necessary, otherwise they can't be imported with the new interpreter.
In the official repos they just [bump the pkgrel](https://github.com/archlinux/svntogit-community/search?p=1&q=python+3.10+rebuild&type=commits) in this case. I think this makes sense on AUR as well, so users don't forget to rebuild their packages or have to go manually over the leftovers in the `python3.9` path.
So I would suggest incrementing pkrel at least on packages that have a python prefix, ideally everything that contains py modules or links against it. What do you think?

**Comment by acxz** [comment]
That's a nice idea, but just some extra work on the end of AUR package maintainers. I would recommend following this reddit post for users on updating their AUR packages to python 3.10. https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/
