### ISSUE TITLE
[ardupilot-gazebo-sitl-git] C++ 17 related error

### ISSUE THREAD

**Issue by AchmadFathoni** [acxz/pkgbuilds#157]
WIthout `-DCMAKE_CXX_STANDARD_REQUIRED=ON `, this package will fallback to C++11 and then fail to build

**Comment by acxz** [comment]
I believe this issue should be resolved at the upstream level instead of try to add cmake flags in the PKGBUILD.

Here is the upstream issue: https://github.com/khancyr/ardupilot_gazebo/issues/47

**Comment by acxz** [comment]
Patched with 720e074

**Comment by acxz** [comment]
released upstream
