### ISSUE TITLE
please update recastnavigation package

### ISSUE THREAD

**Issue by LW-archlinux** [acxz/pkgbuilds#163]
An openmw dev has convinced Debian to use a recent git commit as base for a new recastnavigation pacakge.
see https://packages.debian.org/source/sid/recastnavigation

Openmw ubuntu ppa uses that version and I am also using it for my local openmw trunk build.

Please update so aur openmw-git can use it also.

**Comment by acxz** [comment]
Hello @LW-archlinux! Thanks for creating an issue about this.

The AUR `recastnavigation` package follows the github releases. As such I will not update the package unless there is a new release tagged by the upstream folks at https://github.com/recastnavigation/recastnavigation, no matter what Debian or Ubuntu use.

There does exist `recastnavigation-git` which the AUR `openmw-git` package should directly depend on if it needs that is more recent that the latest upstream release.

Another solution could be to create an AUR package called `recastnavigation-<commit_id>`, based on the PKGBUILD that you have created for the associated PR. However, I currently don't have the bandwidth/interest in creating another package. But feel free to create it yourself.
