### ISSUE TITLE
[python-ray] fails to build

### ISSUE THREAD

**Issue by andrewpak** [acxz/pkgbuilds#170]
When trying to install ray i am geting this error

```
nvidia-utils-495.46-2-x86_64.pkg.tar.zst failed to download
 Total ( 1/34)                                                                         492.1 MiB  59.8 MiB/s 00:08 [####################################################################] 100%
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from america.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.lty.me : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.wtnet.de : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.cyberbits.eu : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from archmirror.it : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from de.arch.mirror.kescher.at : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from phinau.de : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from europe.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.f4st.host : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from archlinux.uk.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from archlinux.mailtunnel.eu : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.chaoticum.net : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.telepoint.bg : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.pseudoform.org : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from archlinux.thaller.ws : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from asia.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.cyberbits.asia : 
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from archlinux.za.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'nvidia-utils-495.46-2-x86_64.pkg.tar.zst' from mirror.theash.xyz : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
```

**Comment by acxz** [comment]
Can you mention the command you used? And post the complete output. From what you have posted looks like you have an issue with your mirrorlist.

Try `yay -S python-ray`

**Comment by andrewpak** [comment]
yay -S python-ray

**Comment by andrewpak** [comment]
Quick question, why do I even have nvidia utils? I don't have any nvidia hardware and how does not pertain to ray if that's the error I'm getting when installing ray?

**Comment by andrewpak** [comment]
Thanks, I appreciate your fast responses.

When I get back on my computer I'll see if I can update my mirrors and try again / troubleshoot it as well.

**Comment by andrewpak** [comment]
Yeah, I did a system update now with `sudo pacman -Syuu` then ran `yay -S python-ray` and it gets further along in the installation of `python-ray` then i get this new error
`patching file bazel/ray_deps_setup.bzl
Hunk #1 FAILED at 236.
1 out of 1 hunk FAILED -- saving rejects to file bazel/ray_deps_setup.bzl.rej
patching file thirdparty/patches/grpc-remove-distutils.patch
The next patch would delete the file thirdparty/patches/grpc-default-initialization.patch,
which does not exist!  Assume -R? [n] 
` 
When I hit enter it just fails, not sure what the other option is? -R maybe? But I have no idea what that does.

**Comment by andrewpak** [comment]
Still trying to figure this out.

I looked into what you said about unsync mirrors. So I went and updated my mirror list by generating a fresh local mirror list on the arch page that generates mirrors then pasting said mirrors into my '../pacman.d/mirrorlist' , this really didn't do anything so I don't believe that's the problem. I believe my mirrors have been fine the whole time. But whatever I got more local mirrors now.

I also tried compiling from source according to the ray docs and that also does not work. Similar issue with this bezel, bazel thing (whatever that is).

What I have narrowed it down to is that 'ray' is not supported for newer versions of python. According to their wiki, even 3.9 is not fully supported. So it may be a python version issue.

I was able to install ray in a couple vm's (Debian and Slackware) and macOS Catalina with no problems through pip.

It's really kinda a shame cause this is the only package really giving me issues on Arch. 

Is this package working for you? What version of python are you running?

**Comment by andrewpak** [comment]
Yeah I think it may be a 3.10 issue, cause I believe the versions of python I have on those other machines is 3.9

I even tried just using pip but I think I broke pip when doing a system update at some point and removing some files in order to force the update.

Fingers crossed it isn't something else. 

Thanks again for working on this.

**Comment by acxz** [comment]
with 1.11, the ray package is now patched, closing this issue. Feel free to comment on this issue if you still encounter errors.

**Comment by andrewpak** [comment]
Just a quick question before I try this, and it is definitely my lack of knowledge on how dependencies work, but as I am reading through the list of dependencies it wants to install, I see some things I already have on my system, i.e. jre/openjdk (just checked my jre/jdk is version 17 and this dependency seems to be version 11). 

Also, I see python-pip as a dependency also, and I know it is recommended not to use pip on arch linux. Also wondering if this is going to be a problem and how this works? Just don't want to break anything as I kinda need these things to be working for some classes I'm currently in.

Will installing these dependencies mess with other software I have of different versions?

**Comment by acxz** [comment]
You mind posting the output?

> Will installing these dependencies mess with other software I have of different versions?

It could, if your other software is not installed correctly in the first place.

`python-pip` is used to install the package that is locally built. It is not recommended to run `sudo pip install`. Whenever you use pip as a user you should use it as `pip install --user`. This is true not just for Archlinux but for all cases of using pip. If you really want to know read the pip docs: https://pip.pypa.io/en/stable/

As for the java version that is most likely due to Bazel the build system used. It is totally fine to have multiple installs of java on your system as well. See java archlinux page for more info, specifically on how to set your default java version: https://wiki.archlinux.org/title/Java#Switching_between_JVM

**Comment by andrewpak** [comment]
I am pretty sure most of the software I currently have is installed correctly. I recently did a fresh arch install and I have only installed with pacman for the most part. I built openmpi and mpy4py from source recently and thats kinda what I am afraid of messing up the most.[](url
![raydependencies](https://user-images.githubusercontent.com/91777106/158706037-aa366109-d641-48ff-b17e-01ebf1d5eb61.png)
)

**Comment by acxz** [comment]
Ultimately the decision is up to, but I don't see anything there that will mess up your source installs of openmpi/mpi4py.

**Comment by andrewpak** [comment]
![2022-03-16_19-20](https://user-images.githubusercontent.com/91777106/158707134-00e788a9-6215-44c7-bfd8-4d27e61596d9.png)


This happened after it connected to some bazel server. further up it says bazel crashed due to an internal error. 

"unsafe.StringUnsafe" ... sometimes these compiler messages,.. 

 It threw a ExceptionInInitializeError.

**Comment by andrewpak** [comment]
I see some bazel and pip directory now in .cache also. Not too sure about this .cache directory, or bazel, gonna have to figure this out later.

**Comment by acxz** [comment]
For ~/.cache: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

You can delete the bazel directory as it is a build artifact.

**Comment by andrewpak** [comment]
I'm gonna see if I can build ray from source again when I have the time. 

It seems like whatever happened before it crashed is on my system now. I see the java 11 jdk also when I check archlinux-java status. Bazel seems to have installed, the command bazel --version is recognized. It also looks like it installed some programs I was meaning to install anyways. If something is a 'build artifact' does it still function as normal?

Strange this isn't working if it is working on your end. It seems like everything installed except for ray.
