### ISSUE TITLE
[vgrep] go dependency should only be build-time

### ISSUE THREAD

**Issue by BrainDamage** [acxz/pkgbuilds#177]
go compiler statically builds files, so runtime dependency is unnecessary.

This can be confirmed by checking with lddtree:

```
lddtree $(which vgrep)
/usr/bin/vgrep (interpreter => /lib64/ld-linux-x86-64.so.2)
    libc.so.6 => /usr/lib/libc.so.6
```

**Comment by acxz** [comment]
thx for the report! Do you mind creating a PR for this fix?
