### ISSUE TITLE
[python-pyqt5-sip4] Failing to build due to 'qt5-quick3d'

### ISSUE THREAD

**Issue by FilCo98** [acxz/pkgbuilds#180]
Hi, I'm trying to install ros-noetic-desktop-full, but during build of this package, the build fails with error "failed to build dependency 'qt5-quick3d'". I'm fairly ignorant in AUR package build mechanics, so I tried installing the dependency 'qt5-quick3d'. This didn't work, as well it didn't work trying to install this package on its own, even if installing it on its own just throws a build error and doesn't specify what kind. I am using baph as a AUR helper. Do you know if it is a problem with the package or my setup? Thanks for you time.

**Comment by acxz** [comment]
AUR helpers can be tricky, they are so many of them and each with their own quirks. The only AUR helpers I test with are `paru` and `yay`. I recommend you try to install `ros-noetic-desktop-full` with `paru`.

Please try again and report the error you are facing as a codeblock with triple backticks. Try to get more of the error message if possible.

**Comment by FilCo98** [comment]
Thank you very much, I unfortunately reached some limit (I guess AUR's), and I'm returning an HTTP error 429. I'll wait until tomorrow to check if it works out with paru.

**Comment by acxz** [comment]
I just checked with a clean chroot build with paru and it worked for me.

> an HTTP error 429

This seems like a weird error, maybe the AUR was down, but there shouldn't be a limit from the cloning the AUR PKGBUILDs to build the package.

**Comment by FilCo98** [comment]
```
Starting build()...
Traceback (most recent call last):
  File "/sbin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.6.1', 'console_scripts', 'sip-build')())
  File "/sbin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'python-pyqt5-sip4-5.15.6-2': 
error: packages failed to build: python-pyqt5-sip4-5.15.6-2
```
Error persists for this package. I have to say that paru detects (at the start of the installation process) the conflict with python-pyqt5. Maybe it's just dependency hell.

**Comment by acxz** [comment]
That seems familiar to #175 
can you try the solution mentioned there? i.e. building in a clean chroot. with paru you can do that with `paru --chroot`.

**Comment by FilCo98** [comment]
```
error: target not found: ros-noetic-cpp-common
error: target not found: ros-noetic-catkin
==> ERROR: 'pacman' failed to install missing depend
encies.
==> Missing dependencies:
  -> cmake
  -> ros-build-tools
  -> ros-noetic-cpp-common
  -> ros-noetic-catkin
  -> boost
==> ERROR: Could not resolve all dependencies.
==> ERROR: Build failed, check /var/lib/aurbuild/x86
_64/phil/build
```

Alright I managed to create a localrepo and to call `paru --chroot -S ros-noetic-desktop-full`, but most packages fail to build in the same way as above (even though of course the dependencies vary). It seems to me as if paru is unable to wrap pacman or doesn't look for packages in the AUR and only in the official repo for dependencies.

That being said I managed to build python-pyqt5-sip4 using the chroot without it throwing that build error, the one in #175.

**Comment by acxz** [comment]
No worries at all.

You should be able to do `paru -Syu ros-noetic-desktop-full --chroot`. Using `-Syu` will ensure paru updates/rebuilds the AUR packages in your local repo. So that during the chroot build it can find those packages. We can't really discern the root cause of the error with just what you have shared here. Feel free to post the entire log.

**Comment by acxz** [comment]
Okay let's start with a smaller piece. Can you try to install `ros-noetic-desktop` via `paru -Syu ros-noetic-desktop --chroot`. You can also set a chroot option in the paru configuration file, so you don't need to type `--chroot` each time, which I recommend.

**Comment by FilCo98** [comment]
I just tried, but again it fails all packages with the same error.
```
error: failed to download sources for 'python-rosdistro-0.8.3-1': failed to run: makechrootpkg -cu -r /var/lib/aurbuild/x86_64 -D /home/phil/.localrepo -d /var/cache/pacman/pkg/ -- -ofA: 
```
I believe it is paru not searching the AUR for the dependencies, but I may be mistaken.

**Comment by acxz** [comment]
yeah it seems so, I'd say first try to make sure that paru can download any random AUR package. Maybe there is some configuration with paru chroot that you are not doing correctly? Asking at the paru github might get u some better help or even on the archlinux matrix chat. https://matrix.to/#/#archlinux:archlinux.org

**Comment by FilCo98** [comment]
I'll try that, thank you very much.

**Comment by acxz** [comment]
@FilCo98 did you ever get this package compiling?
