### ISSUE TITLE
[python-mlflow] missing dependency python-azure-storage-blob

### ISSUE THREAD

**Issue by rmsc** [acxz/pkgbuilds#183]
The dependency is missing from AUR, so no way to build the package.

**Comment by acxz** [comment]
Feel free to create the dependent package on the AUR.

> so no way to build the package.

If you still want to build it, you can clone the PKGBUILD and building with `makepkg -d` which specifies don't check for dependencies and `python-mlflow` will build successfully.

**Comment by rmsc** [comment]
> If you still want to build it, you can clone the PKGBUILD and building with `makepkg -d` which specifies don't check for dependencies and `python-mlflow` will build successfully.

Are you saying `python-azure-storage-blob` is not really a dependency? Shouldn't it then be removed from the `PKGBUILD`?

**Comment by acxz** [comment]
It is listed as a dep in the upstream's `setup.py`, but is not required to build it. I would assume if you want to use a certain functionality provided by this dep it won't work, but you can still use the rest of the package.

**Comment by acxz** [comment]
> Shouldn't it then be removed from the PKGBUILD?

I'll do this when upstream makes it optional in their `setup.py` script, as I want to follow upstream as close as possible.

**Comment by acxz** [comment]
Looks like in later versions, `python-azure-storage-blob` is not required for this package and is removed from the deps. Closing this issue, with the removal of `python-azure-storage-blob` from `makedepends`.
