### ISSUE TITLE
[python-databricks-cli] configparser dependency missing

### ISSUE THREAD

**Issue by PhilipMay** [acxz/pkgbuilds#20]
I am relatively sure that this needs configparser and it is forgotten in the build file. Could you please check that? Thanks!

**Comment by acxz** [comment]
Thx for the concern, however, see the following: https://docs.python.org/3/library/configparser.html
`configparser` is part of python 3 now. There is no separate `python-configparser` package.

**Comment by PhilipMay** [comment]
> Thx for the concern, however, see the following: https://docs.python.org/3/library/configparser.html
> `configparser` is part of python 3 now. There is no separate `python-configparser` package.

Well - yes and no.
You are also the maintainer of `python-mlflow` - right? This package has a dependency to databricks-cli. When I start mlflow I get this error:

``` 
$ mlflow 
Traceback (most recent call last):
  File "/usr/bin/mlflow", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser>=0.3.5' distribution was not found and is required by databricks-cli
```

Can you please review this?

**Comment by PhilipMay** [comment]
I think it is because databricks-cli wants to be python 2 compatible.

**Comment by PhilipMay** [comment]
I made the AUR package: https://aur.archlinux.org/packages/python-configparser/

**Comment by acxz** [comment]
As you quoted that package is only for python versions up to 3.5. Arch is on 3.8.

**Comment by PhilipMay** [comment]
> As you quoted that package is only for python versions up to 3.5. Arch is on 3.8.

Yes that's true. But the missing dependency has other side effects like here: https://github.com/acxz/pkgbuilds/issues/21

**Comment by acxz** [comment]
Upstream PR: https://github.com/databricks/databricks-cli/pull/287

**Comment by acxz** [comment]
Upstream has released a new version with the fix. Removing patch and closing this issue.
