### ISSUE TITLE
[qgroundcontrol] build failed for aarch64

### ISSUE THREAD

**Issue by petronny** [acxz/pkgbuilds#201]
```
moc /build/qgroundcontrol/src/qgroundcontrol-4.2.3/libs/qmlglsink/gst-plugins-good/ext/qt/qtwindow.h
compiling moc_qtwindow.cpp
moc /build/qgroundcontrol/src/qgroundcontrol-4.2.3/libs/qmlglsink/gst-plugins-good/ext/qt/qtitem.h
compiling moc_qtitem.cpp
linking staging/QGroundControl
/usr/bin/ld: skipping incompatible /build/qgroundcontrol/src/qgroundcontrol-4.2.3/build/libs/airmap-platform-sdk/linux/Qt.5.15/libairmap-cpp.so when searching for -lairmap-cpp
/usr/bin/ld: cannot find -lairmap-cpp: No such file or directory
/usr/bin/ld: skipping incompatible /build/qgroundcontrol/src/qgroundcontrol-4.2.3/build/libs/airmap-platform-sdk/linux/Qt.5.15/libairmap-cpp.so when searching for -lairmap-cpp
collect2: error: ld returned 1 exit status
make: *** [Makefile:2983: staging/QGroundControl] Error 1
```

Build log: https://github.com/arch4edu/cactus/runs/7073368207?check_suite_focus=true

PS. You can find the latest new build log at https://arch4edu.github.io/ if it's updated on AUR.

**Comment by petronny** [comment]
Oh, I just find that aarch64 is actually not in the PKGBUILD.
If you are not interested in building qgroundcontrol for aarch64 then this issue can be closed.
No idea why I added it for aarch64 anyway.

**Comment by acxz** [comment]
Yeah I don't think upstream supports aarch64. I'll close this for now as it is more of an upstream feature request. Unless some Arch user wants qgroundcontrol for aarch64, we'll just slide it under the rug for now ;)

**Comment by petronny** [comment]
Hi, I just look a little more on this.

The reason to the error is the airmap library is from a deb package for x86_64. So it can't be used on aarch64.
So there are two ways to solve this, disable the airmap support or build airmap for aarch64.

Currently I disable the airmap support and then [successfully build on aarch64](https://github.com/arch4edu/arch4edu/commit/930dadd22e1c9ca29b1791e05ae468b6118c4be2).

About building airmap for aarch64, I'll give it a try later.
