### ISSUE TITLE
[python-mlflow] 1.28 -> 1.29

### ISSUE THREAD

**Issue by fengwang** [acxz/pkgbuilds#209]
Mlflow 1.29 is release two weeks ago: https://github.com/mlflow/mlflow/releases/tag/v1.29.0

**Comment by acxz** [comment]
thanks for the report, im a bit busy atm, but feel free to send a PR and I'll merge it in!

**Comment by acxz** [comment]
resolved with [e23169d](https://github.com/acxz/pkgbuilds/commit/e23169d76c4c3d8e11d3d8748d5159db5a0d18fa)
