### ISSUE TITLE
[python-mlflow] extra features

### ISSUE THREAD

**Issue by fengwang** [acxz/pkgbuilds#210]
The [mlflow quick start page](https://mlflow.org/docs/latest/quickstart.html) shows extra features such as pipeline and 3rd-party tools can be installed optionally. Would it be possible to include them in this pkgbuild?

**Comment by acxz** [comment]
Feel free to send a PR this way!

**Comment by acxz** [comment]
closed with [e23169d](https://github.com/acxz/pkgbuilds/commit/e23169d76c4c3d8e11d3d8748d5159db5a0d18fa)

You'll have to make sure you manually download the optdepends to get the corresponding feature set of the extra features.
