### ISSUE TITLE
[python-torch-geometric 2.1.0-1] ModuleNotFoundError: No module named 'torch_sparse'

### ISSUE THREAD

**Issue by nihil39** [acxz/pkgbuilds#219]
Hi, 

I successufully installed this package but when I simply try to import it in an empty python file, I get the following error.

```
File "/usr/lib/python3.10/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
ModuleNotFoundError: No module named 'torch_sparse'
```

Should torch_sparse be a dependency of pytorch geometric? 

Thank you.

**Comment by acxz** [comment]
Can you provide the import line that you are using to reproduce the error?

**Comment by nihil39** [comment]
Just this simple snippet

```
import torch
import torch.nn as nn
import torch_geometric
```

Note that using only PyTorch (the first two lines) it works with no problem

**Comment by nihil39** [comment]
The bug is reproducible, look at [this](https://bbs.archlinux.org/viewtopic.php?pid=2088155) forum post. 

I think we have to update Pytorch Geometric PKGBUILD to require torch_sparse as a dependency and update the torch sparse [package](https://aur.archlinux.org/packages/python-pytorch_sparse) which is clearly outdated and unmaintained.

**Comment by acxz** [comment]
Yep, I can reproduce the bug as well. Looks like for the installation dependencies we also need to look at the following: https://github.com/pyg-team/pytorch_geometric#pytorch-113

**Comment by acxz** [comment]
I went ahead and added the deps to the package. You may need to open another issue of `python-torch-sparse` not building successfully though.
