### ISSUE TITLE
[python-uvicorn] package file conflicts

### ISSUE THREAD

**Issue by PhotonQuantum** [acxz/pkgbuilds#22]
It seems that there's an [issue](https://github.com/encode/starlette/issues/850) in the upstream package.

The package will release a `LICENSE.md` file under `/usr`, littering the filesystem, and causing a conflict with the `python-starlette` package, which has the same packaging issue.

Maybe we should move this file to its package dir as a temporary workaround before the upstream fixes this problem?

**Comment by acxz** [comment]
Ah that is a problem, I’m a bit busy for the rest of the week, but feel free to create a PR and I’ll merge and push it out to the AUR with a click!

**Comment by PhotonQuantum** [comment]
The upstream issue is fixed in [uvicorn/#627](https://github.com/encode/uvicorn/pull/627).
So there's no need to apply a temporary patch any more ~

**Comment by acxz** [comment]
Sweet, however this issue will be fixed with a new release so let's close it until that happens.

**Comment by tonybenoy** [comment]
@acxz  the version has been bumped please do check

**Comment by acxz** [comment]
Thx for the reminder, new version is out on the AUR now.
