### ISSUE TITLE
[python-vispy 0.12.1-1] python-setuptools-scm-git-archive is no longer available

### ISSUE THREAD

**Issue by rurigk** [acxz/pkgbuilds#221]
Package: [python-vispy](https://aur.archlinux.org/packages/python-vispy) 0.12.1-1

Package dependency `python-setuptools-scm-git-archive` is not available anymore

I think `python-setuptools-scm-git-archive` is obsolete since `setuptools_scm >= 7.0.0` supports git by itself

And we have [python-setuptools-scm](https://archlinux.org/packages/community/any/python-setuptools-scm/) 7.1.0-1 in the repos

**Comment by acxz** [comment]
Looks like `python-setuptools-scm-git-archive` is required by upstream:

https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/setup.py#L97

The solution would be to create an issue upstream and submit the corresponding fix as a pull request to https://github.com/vispy/vispy

You can then submit a PR to this repo adding that PR as a patch in the PKGBUILD.

When you make the upstream issue if you can link it here, that would help us keep track of the issue. Thanks for reporting!

**Comment by wuyudi** [comment]
I patched it: https://aur.archlinux.org/packages/python-setuptools-scm-git-archive

**Comment by acxz** [comment]
Thanks for creating the package!
