### ISSUE TITLE
[python-hydra-core] makedepends seems mailformed.

### ISSUE THREAD

**Issue by otakutyrant** [acxz/pkgbuilds#229]
I used pikaur to upgrade the system and it reported an error: `:: error: Can't resolve dependencies for AUR package 'python-hydra-core':` And I found out that there was a comma after `'java-runtime>=11'` in the PKGBUILD.

**Comment by acxz** [comment]
Nice find, do you mind making a PR for it?

**Comment by otakutyrant** [comment]
Okay, wait a moment.

**Comment by otakutyrant** [comment]
Today because of the upgrade of Python 3.10 to Python 3.11 I want to rebuild all AUR packages and stuck in this package again. Could you update the PKGBUILD please?

**Comment by acxz** [comment]
Sorry for the late response. Package is updated with your fix. Thanks for the contribution!!!!
