### ISSUE TITLE
`python-argparse` must be removed as dependencies.

### ISSUE THREAD

**Issue by dreirund** [acxz/pkgbuilds#238]
`python-argparse` must be removed from the `depends` and `makedepends` and `checkdepends` arrays of all packages, see [&nearr;&hairsp;here](https://bugs.archlinux.org/task/78484).

It applies at least to `ardupilot-copter-sitl`.

Thanks for maintaining!

**Comment by acxz** [comment]
Closed with [86f47fc](https://github.com/acxz/pkgbuilds/commit/86f47fc87a57cfb267d300020d32b87686d449af)
