### ISSUE TITLE
[python-pyqt5-sip4] fails to build

### ISSUE THREAD

**Issue by LikeSmith** [acxz/pkgbuilds#242]
When building package, get error "sip-build: command not found."  I this package installed before through yay, so all dependencies should be installed.  I have confirmed that sip4 is installed, but it doesn't contain a "sip-build" binary or script.

**Comment by LikeSmith** [comment]
That package is mutually exclusive with sip4 from AUR, which is required by other packages on my system, and is listed as a valid dependency option for this package.

**Comment by KavinTheG** [comment]
I am also encountering this issue. Were you able to found a fix?

**Comment by FabioLolix** [comment]
`python-pyqt5-sip4` don't depends on `sip4` and builds fine with `sip`, you can build `python-pyqt5-sip4` with `devtools` specifically with  `extra-x86_64-build` command, https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot `python-pyqt5-sip4` don't have other depends on AUR packages so you don't have to setup a local repo

**Comment by zijian-x** [comment]
Beware of the compiling eating all of your RAM and thus it will likely hang forever, if you have enabled parallel compiling for `make` by default via env var `MAKEFLAGS=-j` - you have to first clear it from the shell env and then build the package.

**Comment by acxz** [comment]
dup #175
