### ISSUE TITLE
[python-safetensors] fails during check step

### ISSUE THREAD

**Issue by moghingold** [acxz/pkgbuilds#248]
This is the output of makepkg -i on AUR target python-dm-tree: https://pastebin.com/1UZ0E7a3

This package seems to be failing on self-tests that run before the package is installed, so it fails to find itself and thus fails those tests.

The package installs successfully when I comment out this block of the PKGBUILD file:

```
check() {
  cd "safetensors-${pkgver}/bindings/python"
  pytest tests/
}
```

However, leaving out the checks is probably not the best solution. I tried manually re-installing python-safetensors after the first install and still failed one test. That output is here: https://pastebin.com/QXY39x5k

It's now failing because it cannot find module 'paddle'.  However, this is provided by python-paddlepaddle which is not specified as a dependency of python-safetensors. Should this test be patched out, or should python-paddlepaddle be added as a dependency of python-safetensors?

**Comment by acxz** [comment]
Name should be edited for the package which is hosted here that fails to build.
Also please add a more description title than "fails to build".

**Comment by acxz** [comment]
Closing this issue as python-safetensors is not part of this repo. Please post any issues to its AUR page: https://aur.archlinux.org/packages/python-safetensors

Re: python-dm-tree, python-safetensors is not in its dependency chain and python-dm-tree should be able to install successfully, if not please post an issue that is directly related to that package.
