### ISSUE TITLE
[python-ray] Wrongly named dependency python-prometheus-client

### ISSUE THREAD

**Issue by carlsmedstad** [acxz/pkgbuilds#249]
Hey :wave: 

`python-ray` has an optional dependency to `python-prometheus-client` but `python-prometheus_client` is the package name for that package: 

```sh
$ paru -Ss python-prometheus_client
extra/python-prometheus_client 0.16.0-2 [0B 622.60KiB] [Installed]
    Prometheus instrumentation library for Python applications
```

**Comment by carlsmedstad** [comment]
Same with `python-aiohttps_cors`:

```sh
$ paru -Ss python-aiohttp-cors
extra/python-aiohttp-cors 0.7.0-8 [30.28KiB 141.60KiB]
    CORS support for aiohttp
```

**Comment by acxz** [comment]
Done with [5b70518](https://github.com/acxz/pkgbuilds/commit/5b70518ca811c4a2d3b74e89c84bcac1ed94b0b3)
