### ISSUE TITLE
[directfb] ** DirectFB compilation requires fluxcomp ***

### ISSUE THREAD

**Issue by djringjr** [acxz/pkgbuilds#25]
** DirectFB compilation requires fluxcomp ***

Unless you are compiling from a distributed tarball you need fluxcomp
available from git://git.directfb.org/git/directfb/core/flux installed
in your PATH.

**Comment by acxz** [comment]
Thanks for reporting the error, unfortunately I do not have much time this upcoming week so feel free to make a PR to fix this issue. I assume a `fluxcomp-git` package will have to be created from the following url: git://git.directfb.org/git/directfb/core/flux.git  and have that as a makedep of this package.
