### ISSUE TITLE
[python-vispy] fails due to missing 'oldest-supported-numpy'

### ISSUE THREAD

**Issue by brisvag** [acxz/pkgbuilds#251]
I have `python-oldest-supported-numpy` from the aur installed

```
aur/python-oldest-supported-numpy 2022.11.19-1 (+2 0.02) (Installed)
```

but I still get the following error:

```
ERROR Missing dependencies:
	oldest-supported-numpy
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by acxz** [comment]
Looks like that may have been a typo in the PKGBUILD. In the latest version of python-vispy, python-oldest-supported-numpy is not needed and has been removed from the PKGBUILD. Thus this error should be resolved.

If you have any other issues please open up another issue.
