### ISSUE TITLE
`python-pyqt5-sip4` fail to build

### ISSUE THREAD

**Issue by LumenYoung** [acxz/pkgbuilds#252]
I've done a bit of research, the direct cause of this problem is the missing command `sip-build`.

This is caused by the required `sip4` package, which doesn't ship with the `sip-build`. But the command exists in `extra/sip`.

My `ros-noetic-desktop` installation failed due to this problem. I hope someone can offer me some insight on how to solve this problem.

Bests,
Lumen

**Comment by FabioLolix** [comment]
> This is caused by the required sip4

`python-pyqt5-sip4` have a makedepends on `sip` not `sip4`

see also https://github.com/acxz/pkgbuilds/issues/242#issuecomment-1646621920

Duplicate of #242

**Comment by LumenYoung** [comment]
> > This is caused by the required sip4
> 
> `python-pyqt5-sip4` have a makedepends on `sip` not `sip4`
> 
> see also [#242 (comment)](https://github.com/acxz/pkgbuilds/issues/242#issuecomment-1646621920)
> 
> Duplicate of #242

Thank you for your reply. I managed to solve this issue with clean root compilation, thanks!

**Comment by acxz** [comment]
dup of #175
