### ISSUE TITLE
[octomap] install not working with C++20 compiler

### ISSUE THREAD

**Issue by RishabhSk7** [acxz/pkgbuilds#267]
installing Octomap from aur (which is on v1.9.8) with The C++ 20 compiler gives  `error: template-id not allowed for constructor in C++20`. Apparently the simple-template-id is no longer valid as the declarator-id of a constructor or destructor.

Tbh I don't have too much idea on how to go around and fix this, but Octomap c1.10.0 seems to compile fine without any issues. Please update the package to 1.10.0.

**Comment by acxz** [comment]
Closed with #265
