### ISSUE TITLE
[ignition-math] Build error

### ISSUE THREAD

**Issue by acxz** [acxz/pkgbuilds#27]
Upstream issue: https://github.com/ignitionrobotics/ign-math/issues/104

**Comment by acxz** [comment]
TLDR: Install `swig-git` instead of `swig`

**Comment by Ramdambo** [comment]
Developers have moved over to Github. New repo is https://github.com/ignitionrobotics/ign-math
Version on Bitbucket is bugged since they forgot to include a header in one source file.

**Comment by acxz** [comment]
ah yep u right, I'm a bit busy this week, but feel free to make a PR and I'll merge it in a jiffy.

**Comment by Ramdambo** [comment]
I'll try, though I don't have any experience with writing PKGBUILDs

**Comment by acxz** [comment]
Good time to learn as any! Just submit a PR, we can go through it together ;)

**Comment by Ramdambo** [comment]
Just created the pull request!
Build works on my machine, would suggest you try it yourself though, I am not 100 percent confident.

**Comment by acxz** [comment]
mm in this case we will have to patch the package with that commit. If you are interested in doing the fix take a look at https://wiki.archlinux.org/index.php/Patching_packages or I could take care of it later today prob,

Or someone could create a ignition-math-git package and use that.

**Comment by acxz** [comment]
Also hint for patching the package you can pull the patch directly from the github repo like so: https://github.com/ignitionrobotics/ign-math/commit/fdbd226d70885e85e265d7c61cfa9014bee1a33a.patch
and add this file to this url to the `source` entry take a look at [this](https://github.com/acxz/pkgbuilds/pull/31/commits/0a7809c5bc7fe92fa916b72c88dc69ba6124b013) for reference.

**Comment by Ramdambo** [comment]
Oh okay, read that too late. Patched it myself, pushing in a minute!

**Comment by MauroMombelli** [comment]
something is still broken for me:
```
warning: Tag 'TCL_SUBST' at line 237 of file '/tmp/makepkg/ignition-math/src/ign-math-ignition-math6_6.4.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'PERL_PATH' at line 2116 of file '/tmp/makepkg/ignition-math/src/ign-math-ignition-math6_6.4.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'MSCGEN_PATH' at line 2138 of file '/tmp/makepkg/ignition-math/src/ign-math-ignition-math6_6.4.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
make[1]: *** [CMakeFiles/Makefile2:306: src/CMakeFiles/math.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Built target doc
make: *** [Makefile:161: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by acxz** [comment]
Can you do a ‘yay -Syu ignition-math —rebuild-tree’?

**Comment by MauroMombelli** [comment]
it did work, so it was just cached stuff, i guess. Thanks.

**Comment by acxz** [comment]
Glad to hear!

**Comment by acxz** [comment]
With ign-math 6.5.0 this build error does not pop up.
