### ISSUE TITLE
soundnode-app-bin: Harfbuzz version too old (1.2.7)

### ISSUE THREAD

**Issue by TitusLabienus** [acxz/pkgbuilds#29]
I've installed soundnode-app-bin. Running $soundnode results in following error:

(soundnode:31689): Pango-ERROR **: 18:55:48.476: Harfbuzz version too old (1.2.7)
Trace/breakpoint trap (core dumped)

**Comment by TitusLabienus** [comment]
Closed, because duplicate of #1131

**Comment by TitusLabienus** [comment]
Realized that there is a ticket on upstream already:
https://github.com/Soundnode/soundnode-app/issues/1131
If this is an issue on upstream instead of packaging, this one can be closed

**Comment by acxz** [comment]
#7 
In the meanwhile I would recommend you install ‘soundnode-git’

**Comment by TitusLabienus** [comment]
I see. Thank you for the hint with soundnode-git
