### ISSUE TITLE
[triangle] fork available

### ISSUE THREAD

**Issue by MarDiehl** [acxz/pkgbuilds#33]
I want to use triangle as an optional dependency of PETSc, but the inclusion of triangle.h fails with the error
`/usr/include/triangle.h:252:3: error: unknown type name ‘REAL’`. This seems to be related to old syntax (triangle is 15 years old)

The PETSc developers have their modified version of Triangle that works with more recent compilers. Would it be possible to base the AUR on this version? PKGBUILD is attached.

[PKGBUILD](https://github.com/acxz/pkgbuilds/files/4618667/PKGBUILD.log)

**Comment by acxz** [comment]
I see, yeah it would be nice to patch it so that it works, if you could submit a PR that would be great.

**Comment by acxz** [comment]
Also instead of changing the source, I would rather prefer a patch file instead. This is so that the changes can be made on top of the original triangle version and can be tracked against it, instead of PETSc's internal version.

**Comment by acxz** [comment]
Have you taken a look at the following repo: https://github.com/libigl/triangle
They have made some changes on top of the latest release for which a `triangle-git` package can be made. Maybe it works with petsc?

**Comment by acxz** [comment]
Closing this issue with #42
