### ISSUE TITLE
[soundnode] npm ERR! missing script: package

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [acxz/pkgbuilds#35]
soundnode
---------------
error:
`npm run package;linux`
valid:
`npm run package:linux`

[PKGBUILD.zip](https://github.com/acxz/pkgbuilds/files/4621534/PKGBUILD.zip)

**Comment by acxz** [comment]
Sweet thx for finding that issue. If you could submit a PR, I'll go ahead and merge it in.

**Comment by acxz** [comment]
closing this issue as I am not maintaining soundnode anymore
