### ISSUE TITLE
[sdformat] fatal error: urdf_model/model.h: No such file or directory

### ISSUE THREAD

**Issue by goekce** [acxz/pkgbuilds#51]
while building `sdformat` I get the following error:
```
[ 52%] Building CXX object src/CMakeFiles/sdformat9.dir/Types.cc.o
/home/arch/.cache/pikaur/build/sdformat/src/sdformat-sdformat9_9.2.0/src/parser_urdf.cc:30:10: fatal error: urdf_model/model.h: No such file or directory
   30 | #include <urdf_model/model.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```
I have `urdf_model/model.h` already installed in `/opt/ros2/`. Do I have to point there?

**Comment by goekce** [comment]
Installing `urdfdom` from AUR fixes the problem. So it is not an optional dependency.

`urdfdom` installs the ros1 version, but I could not see any differences between `urdfdom` headers for ros1 and ros2.

**Comment by acxz** [comment]
Thanks for catching that @goekce, do you mind creating a PR to change urdfdom from optdepend to depends?

**Comment by goekce** [comment]
I'd love to @acxz ! I'll try it tomorrow.
