### ISSUE TITLE
[openvsp] [build] `SW_SHOWNORMAL` was not declared in this scope

### ISSUE THREAD

**Issue by acxz** [acxz/pkgbuilds#53]
Upstream issue: https://github.com/OpenVSP/OpenVSP/issues/151

**Comment by petronny** [comment]
So would you apply https://github.com/OpenVSP/OpenVSP/commit/970d41dd53bd7307da597a72cde7a1b2b7595b33.patch in openvsp ?

**Comment by acxz** [comment]
Yeah, just need to get around doing so. Probably over the weekend.

**Comment by acxz** [comment]
@petronny decided to just go ahead and add the patch. Thx for the nudge :) Closing the issue.
