### ISSUE TITLE
[python-dm-tree] Bazel java version

### ISSUE THREAD

**Issue by oysstu** [acxz/pkgbuilds#54]
Hi,

Bazel has a hard requirement for java version 11, and will fail if the default java environment is set to e.g. java 8. Adding the following in your build function resolves the issue.

`export JAVA_HOME=/usr/lib/jvm/java-11-openjdk`

**Comment by acxz** [comment]
@oysstu  I can't seem to reproduce this issue even when my default java is 8. I believe bazel will automatically select java 11. 
Can you show the command of `archlinux-java status`?

Maybe you have a local install of java 8 that Arch is not aware of?

**Comment by oysstu** [comment]
archlinux-java status
```
Available Java environments:
java-11-openjdk
java-8-openjdk/jre (default)
```

The error is as follows
```running build
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/tree
copying tree/__init__.py -> build/lib.linux-x86_64-3.8/tree
copying tree/tree_benchmark.py -> build/lib.linux-x86_64-3.8/tree
copying tree/tree_test.py -> build/lib.linux-x86_64-3.8/tree
running build_ext
bazel build //tree:_tree --symlink_prefix=build/temp.linux-x86_64-3.8/bazel- --compilation_mode=opt
FATAL: Could not find system javabase. Ensure JAVA_HOME is set, or javac is on your PATH.
error: command 'bazel' failed with exit status 36
```
Switching to java-11-openjdk solves the issue. I don't think bazel automatically finds the java version it needs unless it's in on the search path. I've had to export JAVA_HOME like this with bazel before in order for it to work for people with different java defaults.

**Comment by oysstu** [comment]
Ok, so the javac binary for java-8 is installed by the package jdk8-openjdk. In that case bazel actually works (with java-8, not java-11 as its supposed to do).

**Comment by acxz** [comment]
Do you think we should close this? Personally hardcoding the java home is not an ideal solution at all. If it works, I would say to keep it as is. When building in a clean chroot in the ideal case, this issue would not pop up at all.

**Comment by oysstu** [comment]
Sure, up to you. At least it's here in case anyone else has the same issue.
