### ISSUE TITLE
[darknet-alexeyab-git] Error when installing files: Can not find file libdark.so

### ISSUE THREAD

**Issue by shatyuka** [acxz/pkgbuilds#60]
Seems they change the library name `libdark.so` to `libdarknet.so` [Commit](https://github.com/AlexeyAB/darknet/commit/78293335dfb1713a3c74b4d1f9425f29ea9043ef)

**Comment by acxz** [comment]
Seems so, thx for reporting. I currently don't have the bandwidth to fix this, but if you make a PR, I'll merge it in a jiffy.
