### ISSUE TITLE
[ignition-math] headerfix.patch did not pass the validity check

### ISSUE THREAD

**Issue by julianoes** [acxz/pkgbuilds#67]
I'm trying to build gazebo including the tree and I get this when it tries to download and build ignition-math:

```
==> Making package: ignition-math 6.4.0-6 (Tue 25 Aug 2020 09:03:03 AM CEST)
==> Retrieving sources...
  -> Found ignition-math-6.4.0.tar.gz
  -> Found headerfix.patch
==> Validating source files with sha256sums...
    ignition-math-6.4.0.tar.gz ... Passed
    headerfix.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
error downloading sources: ignition-math
```

**Comment by acxz** [comment]
Really weird, its totally working for me.
In the directory you are building `ignition-math` can you do a `sha256sum headerfix.patch` and manually try to confirm the checksums.

Only thing I can think of is that you dont have a updated/stable system. What is the version of your `coreutils` package?

**Comment by julianoes** [comment]
Thanks for the quick response. My system should be totally up-to-date.

```
cd .cache/yay/ignition-math
sha256sum headerfix.patch 
9e1619ca8a04ecce7f0fce4779344657670cf4dea2e207136c83cab95c53ddde  headerfix.patch
```

So, I tried to remove the patch:
```
mv headerfix.patch headerfix.patch.bak
```

And now it builds again. So it was stale cached data. I guess that's a yay issue and not your problem :wink:.

**Comment by MaEtUgR** [comment]
I had the exact same issue.
After a system update I did:
```
$ yay -S gazebo --noconfirm --rebuildtree
...
==> ERROR: One or more files did not pass the validity check!
error downloading sources: ignition-math
```

```
$ pacman -Q coreutils
coreutils 8.32-1
```

```
$ sha256sum headerfix.patch
9e1619ca8a04ecce7f0fce4779344657670cf4dea2e207136c83cab95c53ddde  headerfix.patch
```

Based on @julianoes 's input I did: `rm -rf .cache/yay/ignition-math/` and now it continues.

**Comment by acxz** [comment]
@Ramdambo this might help

**Comment by Ramdambo** [comment]
> @Ramdambo this might help

Thanks, I'll check it out as soon as I get the chance.
