### ISSUE TITLE
[silly] Outdated config.guess and config.sub can not compile on aarch64

### ISSUE THREAD

**Issue by jgmdev** [acxz/pkgbuilds#68]
Here are newer config.guess and config.sub in order to be able to compile under aarch64 which can be added to the source array:

'config.guess::http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
'config.sub::http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'

And add to the prepare something like:

cp ../config.guess .
cp ../config.sub .

**Comment by acxz** [comment]
Thx for pointing this out. I currently don't have the bandwidth to fix this myself, but feel free to make a PR for it. I'll merge it in ASAP.
