### ISSUE TITLE
[darknet-alexeyab-git] build missing libraries info

### ISSUE THREAD

**Issue by vfbsilva** [acxz/pkgbuilds#72]
@acxz I know you commented somewhere long ago that:
ilmbase-2.3.0-1-x86_64.pkg.tar.xz
opencv-4.1.0-2-x86_64.pkg.tar.xz
openexr-2.3.0-1-x86_64.pkg.tar.xz
Are needed to build darknet due to some incompatibility I can't recall. Doing a fresh install here I could not find any info and was just lucky I had the packages saved in my google drive. Can you maybe add those comments/tutorial somewhere?

**Comment by acxz** [comment]
Hey @vfbsilva the reason why I took that information down is because it is outdated. You do not need those packages to compile darknet with CUDA anymore as CUDA 11 now compiles with gcc 9.

**Comment by acxz** [comment]
If you have an issue then feel free to post it.

**Comment by vfbsilva** [comment]
Strange I did use that to install it on manjaro. here is my gcc info:
`gcc version 10.2.0 (GCC) `
So  I'm confused. What info can I provide to help you? To be clear: darknet is installed and working but I did install those unneeded libs.
