### ISSUE TITLE
[openvsp] Segmentation falut export STEP file in OpenVSP

### ISSUE THREAD

**Issue by jrparks9469** [acxz/pkgbuilds#74]
**Description**
When I attempt to export a STEP file, I receive a segmentation fault error regardless of the geometry.  This happens both for trimmed and untrimmed STEP files.

**Notes**
It doesn't happen for IGES files, which leads me to believe the error is related stepcode bundled with openvsp. The error doesn't occur when I compile from source on a debian based distribution. Might be able to resolve the problem by building stepcode from source and changing the cmake variables to use that installation rather than the bundled libraries, but I haven't been able to try that.

**Comment by acxz** [comment]
upstream issue: https://github.com/OpenVSP/OpenVSP/issues/155

**Comment by acxz** [comment]
> Might be able to resolve the problem by building stepcode from source and changing the cmake variables to use that installation rather than the bundled libraries, but I haven't been able to try that.

@jrparks9469 you could try using the system wide stepcode library by setting the `-DUSE_SYSTEM_STEPCODE=true` in the PKGBUILD however you might encounter some further errors with ambigous  definitions of `real`.

**Comment by jrparks9469** [comment]
I resolved the issue by building OpenVSP using the following method

```shell
# Create directories
mkdir OpenVSP
cd OpenVSP
mkdir repo build buildlibs

# clone repository
git clone https://github.com/OpenVSP/OpenVSP.git

# CMake libraries in Release mode
cd buildlibs
cmake -DCMAKE_BUILD_TYPE=Release \
-DVSP_USE_SYSTEM_CPPTEST=true \
-DVSP_USE_SYSTEM_LIBXML2=true \
-DVSP_USE_SYSTEM_EIGEN=true \
-DVSP_USE_SYSTEM_FLTK=true \
-DVSP_USE_SYSTEM_GLM=true \
-DVSP_USE_SYSTEM_GLEW=true \
-DVSP_USE_SYSTEM_CMINPACK=true \
-DVSP_USE_SYSTEM_CODEELI=true \
-DVSP_USE_SYSTEM_LIBIGES=false \
../repo/Libraries

make -j8

# CMake VSP in Release mode
cd ../build
cmake ../repo/src/ -DVSP_LIBRARY_PATH=/path/to/OpenVSP/buildlibs \
-DCMAKE_BUILD_TYPE=Release \
-DPYTHON_EXECUTABLE=/usr/bin/python

make

make package
```

I'm not familiar enough with PKGBUILD syntax (though it's probably something I should learn) to figure out how that differs from the method you're using. I didn't need the stepcode library after all.

Hopefully this is helpful

**Comment by acxz** [comment]
Glad you got it figured out, let's keep the issue open until the fixes are propagated into the package.

**Comment by acxz** [comment]
@jrparks9469 I went ahead and updated the pkgbuild with the same build process used for debian based systems. I believe the issue is fixed and I'll close the thread, but if you could test and comment on it that would be great.
