### ISSUE TITLE
[python-vispy] checksum

### ISSUE THREAD

**Issue by liamtimms** [acxz/pkgbuilds#77]
vispy does not build due to failed checksum:

```
python-vispy-0.6.5.tar.gz ... Passed
    vispy.js.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
error downloading sources: python-vispy
```

**Comment by acxz** [comment]
hmm just tested it on my machine and it worked.
Can you try a clean rebuild, most likely the vispy.js.tar.gz file needs to be redownloaded and you are using the previously cached version.

`yay -Syu python-vispy --rebuildtree` make sure to enter `A` when prompted to clean rebuild.

**Comment by liamtimms** [comment]
Ah yep, I did have a cache around. Thanks!
