### ISSUE TITLE
[python-ray] conflicts with mesa-demos

### ISSUE THREAD

**Issue by huyz-git** [acxz/pkgbuilds#79]
```
error: failed to commit transaction (conflicting files)
python-ray: /usr/bin/ray exists in filesystem (owned by mesa-demos)
```

**Comment by acxz** [comment]
thanks for the report @huyz-git  not sure what would be the best solution. It seems like a way forward would be to rename `/usr/bin/ray` from `python-ray` to something else.

Do you have any propositions on resolving this?

**Comment by huyz-git** [comment]
> thanks for the report @huyz-git not sure what would be the best solution. It seems like a way forward would be to rename `/usr/bin/ray` from `python-ray` to something else.
> 
> Do you have any propositions on resolving this?

Since now I doubt whether `python-ray` is actually suitable for being packaging in archlinux, because arch is a rolling distro and `python-ray` it pins its dependency version (https://github.com/acxz/pkgbuilds/issues/80).

**Comment by acxz** [comment]
We can fix that be contributing upstream :)

We could do `py-ray` but honestly I would rather just keep it as is.

**Comment by jan-Kulpas** [comment]
I also have this issue now on Manjaro.

**Comment by acxz** [comment]
Closing this issue as @carlosal1015 is now maintaining this package.
