### ISSUE TITLE
[soundnode] Build Error

### ISSUE THREAD

**Issue by acxz** [acxz/pkgbuilds#8]
Upstream issue: https://github.com/Soundnode/soundnode-app/issues/1138
EDIT: waiting for new upstream release

**Comment by prostomarkeloff** [comment]
@acxz hasn't it been merged already?

**Comment by acxz** [comment]
A new release has not been made yet, I suggest you use `soundnode-git` in the meanwhile.

**Comment by acxz** [comment]
Closing this issue as I am not maintaining soundnode anymore
