### ISSUE TITLE
[libdart] Missing octomap

### ISSUE THREAD

**Issue by petronny** [acxz/pkgbuilds#81]
When building `libdart` in clean chroot, the compiler is seeking for `octomap/octomap.h` which is in `octomap`

**Comment by acxz** [comment]
whoa sorry about that, on it.

Oh also @petronny I have a suggestion for you. You should take a look at @bionade24 's (current ros-melodic-arch lead) [`abs_cd`](https://github.com/bionade24/abs_cd). Here is a current instance of it running: https://abs-cd.oscloud.info/cd_manager/overview/

Not sure how hard it would be to integrate but I think having a public facing web interface for the builds would be super helpful for people to contribute.

**Comment by acxz** [comment]
Fixed with `6.9.5-2`. Moved a bunch of other build "optdeps" into depends. There is still pagmo, but dart has a build problem with pagmo at the moment, so keeping it an optdepend.

**Comment by petronny** [comment]
> @bionade24 's (current ros-melodic-arch lead) abs_cd

I'm working on migrating all build logs to github actions.
About the status page, I'll try to build one.

**Comment by bionade24** [comment]
> > @bionade24 's (current ros-melodic-arch lead) abs_cd
> 
> I'm working on migrating all build logs to github actions.
> About the status page, I'll try to build one.

Nice. But I guess it's against their ToS to use it as a CD. What's trick to use a repo? Maybe a bit offtopic, please send a mail to us all.
