### ISSUE TITLE
[pagmo] pagmo2 needs C++17 compiler standard to build

### ISSUE THREAD

**Issue by Bidski** [acxz/pkgbuilds#85]
See esa/pagmo2#456 and esa/pagmo2#458

The main error I saw was a `conjunction`, `disjunction`, and `negation` are not members of the `std` namespace. These functions were added in C++17.

If we want a short-term patch to make libdart build this will do it, or we can wait for pagmo to merge the PR I submitted

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,6 +9,10 @@
 
 project(dart)
 
+set(CMAKE_CXX_STANDARD 17)
+set(CMAKE_CXX_STANDARD_REQUIRED YES)
+set(CMAKE_CXX_EXTENSIONS NO)
+
 string(TOUPPER ${PROJECT_NAME} PROJECT_NAME_UPPERCASE)
 
 # Use MACOSX_RPATH by default on OS X. This was added in CMake 2.8.12 and
```

**Comment by acxz** [comment]
Thx for the report, instead of patching libdart we should patch our pagmo build with your upstream PR. Feel free to make a PR to patch the pagmo package.

**Comment by Bidski** [comment]
The PR I submitted for pagmo2 has now been merged in. I can look at creating a patch/PR for it tomorrow, unless you get to it first

**Comment by acxz** [comment]
Great!
I'll let you take care of it ;)

**Comment by Bidski** [comment]
See #87
